spring.application.name=visitor-gatepass
server.port=9092

spring.datasource.url=jdbc:mysql://localhost:3306/visitor_gatepass_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# EMAIL SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sadhanalondhe11@gmail.com
spring.mail.password=globuutyrcseyzol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

alerts.sla.timeout-minutes=30
alerts.sla.check-interval-ms=60000



server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always